let prompts = [
    "A breathtaking sunset casting golden hues over a futuristic cyberpunk city skyline, neon lights flickering in the twilight.",
    "A sprawling metropolis in the year 3000, where gravity-defying highways intertwine between glowing skyscrapers.",
    "A tranquil valley with a crystal-clear river reflecting the vibrant colors of a surreal, dreamlike sky.",
    "An ancient dragon soaring above a medieval kingdom, its scales shimmering in the sunlight as knights prepare for battle.",
    "A mystical forest where bioluminescent mushrooms illuminate the paths, and enchanted creatures whisper secrets in the wind.",
    "A neon-drenched cyberpunk city at midnight, filled with holographic advertisements, rain-slicked streets, and shadowy figures in trench coats.",
    "A post-apocalyptic wasteland where the last remnants of humanity survive amidst towering rusted ruins and radioactive storms.",
    "A steampunk world with colossal airships sailing through copper-colored skies, gears and steam hissing as they hover above floating cities.",
    "A gravity-defying world of floating islands covered in lush greenery, connected by glowing energy bridges.",
    "A massive battle between towering mechs and alien creatures in a war-torn futuristic landscape, explosions lighting up the battlefield.",
    "A lush, alien jungle with bioluminescent plants, vibrant creatures with iridescent wings, and floating jellyfish-like organisms drifting in the air.",
    "An ancient temple hidden deep in an enchanted jungle, filled with mythical creatures guarding its untold secrets.",
    "A wizard's tower surrounded by swirling magical auras, where arcane spells crackle in the air and glowing runes hover in mid-space.",
    "A futuristic utopia where artificial intelligence governs society in perfect harmony, with AI-driven architecture morphing at will.",
    "An ancient civilization lost beneath the ocean, where mermaids swim between crumbling ruins illuminated by strange glowing corals.",
    "A high-speed aerial race through a city of floating vehicles, where gravity-defying racers weave through impossible loops and tunnels.",
    "A mind-bending journey through time, where past and future collide in a surreal, ever-shifting landscape of history's greatest moments.",
    "A portal to a parallel universe where physics defy logic, colors bend reality, and landscapes change with every step.",
    "A team of superheroes soaring above a dystopian city, their capes trailing streaks of energy as they battle a cosmic threat.",
    "A secret lair of the world's most notorious supervillain, filled with high-tech gadgets, doomsday devices, and an eerie sense of foreboding.",
    "A galactic voyage through the cosmos, where astronauts explore ancient alien megastructures drifting in the depths of space.",
    "A small town caught in an alien invasion, with eerie spacecraft hovering above and beams of light abducting unsuspecting citizens.",
    "A mysterious city trapped in an endless time loop, where every day resets and only one person remembers the past events.",
    "A fully immersive virtual reality world where players can reshape reality at will, from floating castles to pixelated dreamscapes.",
    "An AI-driven megacity where sentient robots coexist with humans, but an underground resistance fights for control over the mainframe.",
    "A bio-engineered future where humanity has spliced their DNA with animals, creating powerful hybrid species with incredible abilities.",
    "A cybernetic revolution where people merge with machines, transforming into sleek, high-tech cyborgs with superhuman capabilities.",
    "A sprawling factory where sentient robots are mass-produced, but one defective unit gains self-awareness and begins a rebellion.",
    "A secret underground laboratory where nanotechnology has evolved beyond human control, consuming everything in its path.",
    "A quantum physics experiment gone wrong, creating rifts in reality where past, present, and future exist simultaneously."

]