import { StaticImageData } from "next/image";
import { AVATAR } from "../../public/assets/images/images";


export const PROJECT_TEMPLATES = [
  {
    emoji: "🎬",
    title: "Build a Netflix clone",
    prompt:
      "Build a Netflix-style homepage with a hero banner (use a nice, dark-mode compatible gradient here), movie sections, responsive cards, and a modal for viewing details using mock data and local state. Use dark mode.",
  },
  {
    emoji: "📦",
    title: "Build an admin dashboard",
    prompt:
      "Create an admin dashboard with a sidebar, stat cards, a chart placeholder, and a basic table with filter and pagination using local state. Use clear visual grouping and balance in your design for a modern, professional look.",
  },
  {
    emoji: "📋",
    title: "Build a kanban board",
    prompt:
      "Build a kanban board with drag-and-drop using react-beautiful-dnd and support for adding and removing tasks with local state. Use consistent spacing, column widths, and hover effects for a polished UI.",
  },
  {
    emoji: "🗂️",
    title: "Build a file manager",
    prompt:
      "Build a file manager with folder list, file grid, and options to rename or delete items using mock data and local state. Focus on spacing, clear icons, and visual distinction between folders and files.",
  },
  {
    emoji: "📺",
    title: "Build a YouTube clone",
    prompt:
      "Build a YouTube-style homepage with mock video thumbnails, a category sidebar, and a modal preview with title and description using local state. Ensure clean alignment and a well-organized grid layout.",
  },
  {
    emoji: "🛍️",
    title: "Build a store page",
    prompt:
      "Build a store page with category filters, a product grid, and local cart logic to add and remove items. Focus on clear typography, spacing, and button states for a great e-commerce UI.",
  },
  {
    emoji: "🏡",
    title: "Build an Airbnb clone",
    prompt:
      "Build an Airbnb-style listings grid with mock data, filter sidebar, and a modal with property details using local state. Use card spacing, soft shadows, and clean layout for a welcoming design.",
  },
  {
    emoji: "🎵",
    title: "Build a Spotify clone",
    prompt:
      "Build a Spotify-style music player with a sidebar for playlists, a main area for song details, and playback controls. Use local state for managing playback and song selection. Prioritize layout balance and intuitive control placement for a smooth user experience. Use dark mode.",
  }
] as const;



// lib/data/testimonials.ts

export interface Testimonial {
  username: string;
  designation: string;
  text: string;
  image: string | StaticImageData;
  
}

export const testimonials: Testimonial[] = [
  {
    username: "Ananya Roy",
    designation: "Product Designer at Zepto",
    text:
      "FingAI helped me ship a polished landing page in under 10 minutes. The automation is mind-blowing!",
    image: AVATAR.testiOne,
  },
  {
    username: "Rahul Mehta",
    designation: "Full-Stack Developer at TCS",
    text:
      "I was skeptical at first, but FingAI genuinely saves hours of layout and design work.",
    image: AVATAR.testiEight,
  },
  {
    username: "Meera Chopra",
    designation: "Founder of PixelDrop",
    text:
      "I love how intuitive FingAI is. It’s like having a personal frontend developer on my team.",
    image: AVATAR.testiSeven,
  },
  {
    username: "Siddharth Jain",
    designation: "Marketing Lead at Creatix",
    text:
      "Our entire team now uses FingAI to prototype campaigns and microsites. It’s a game-changer.",
    image: AVATAR.testiSix,
  },
  {
    username: "Riya Sen",
    designation: "UI Developer at Accenture",
    text:
      "The design-to-deploy pipeline is crazy fast with FingAI. I’ve never felt more productive.",
    image: AVATAR.testiFive,
  },
  {
    username: "Aditya Sharma",
    designation: "Founder, DevSpark",
    text:
      "FingAI cuts out the repetitive work and lets me focus on features. I use it for every new client now.",
    image: AVATAR.testiFour,
  },
  {
    username: "Sneha Verma",
    designation: "Growth Strategist at Launchpad",
    text:
      "The landing pages generated by FingAI are elegant and convert well. Worth every second.",
    image: AVATAR.testiThree,
  },
  {
    username: "Karan Batra",
    designation: "Freelance Web Developer",
    text:
      "From onboarding to deployment, FingAI delivers. I use it to build MVPs faster than ever.",
    image: AVATAR.testiTwo,
  },
  {
    username: "Tanya D’Souza",
    designation: "Creative Director at Dotcom",
    text:
      "Minimal design meets powerful control. FingAI fits perfectly into my workflow.",
    image: AVATAR.testiNine,
  },
];

export interface FAQ  {
   question: string,
   answer: string
}
export const faq: FAQ[] = 
[
  {
    question: "What is FingAI?",
    answer: "FingAI is an AI-powered website builder that helps you create beautiful, responsive websites without writing a single line of code. Just give it a prompt — and it builds your site for you."
  },
  {
    question: "Do I need to know how to code to use FingAI?",
    answer: "Not at all! FingAI is designed for everyone — from beginners to professionals. You simply describe your idea, and FingAI turns it into a live website."
  },
  {
    question: "Does FingAI support both light and dark themes?",
    answer: "Yes! FingAI supports theme toggling. You can switch between a soft pink & white light mode and a sleek pink & black dark mode."
  },
  {
    question: "Is my website mobile-friendly?",
    answer: "Absolutely. Every website built with FingAI is fully responsive and optimized for phones, tablets, and desktops."
  },
  {
    question: "Can I add animations to my website?",
    answer: "Yes, FingAI includes subtle, minimal animations powered by Tailwind CSS and raw CSS — including fade-ins, hover effects, and gradient text transitions."
  },
  
]
