import { StaticImageData } from "next/image";
import { AVATAR } from "../../public/assets/images/images";

export interface Testimonial {
  username: string;
  designation: string;
  text: string;
  image: string | StaticImageData;
  
}

export const testimonials: Testimonial[] = [
  {
    username: "Ananya Roy",
    designation: "Product Designer at Zepto",
    text:
      "FingAI helped me ship a polished landing page in under 10 minutes. The automation is mind-blowing!",
    image: AVATAR.testiOne,
  },
  {
    username: "Rahul Mehta",
    designation: "Full-Stack Developer at TCS",
    text:
      "I was skeptical at first, but FingAI genuinely saves hours of layout and design work.",
    image: AVATAR.testiEight,
  },
  {
    username: "Meera Chopra",
    designation: "Founder of PixelDrop",
    text:
      "I love how intuitive FingAI is. It’s like having a personal frontend developer on my team.",
    image: AVATAR.testiSeven,
  },
  {
    username: "Siddharth Jain",
    designation: "Marketing Lead at Creatix",
    text:
      "Our entire team now uses FingAI to prototype campaigns and microsites. It’s a game-changer.",
    image: AVATAR.testiSix,
  },
  {
    username: "Riya Sen",
    designation: "UI Developer at Accenture",
    text:
      "The design-to-deploy pipeline is crazy fast with FingAI. I’ve never felt more productive.",
    image: AVATAR.testiFive,
  },
  {
    username: "Aditya Sharma",
    designation: "Founder, DevSpark",
    text:
      "FingAI cuts out the repetitive work and lets me focus on features. I use it for every new client now.",
    image: AVATAR.testiFour,
  },
  {
    username: "Sneha Verma",
    designation: "Growth Strategist at Launchpad",
    text:
      "The landing pages generated by FingAI are elegant and convert well. Worth every second.",
    image: AVATAR.testiThree,
  },
  {
    username: "Karan Batra",
    designation: "Freelance Web Developer",
    text:
      "From onboarding to deployment, FingAI delivers. I use it to build MVPs faster than ever.",
    image: AVATAR.testiTwo,
  },
  {
    username: "Tanya D’Souza",
    designation: "Creative Director at Dotcom",
    text:
      "Minimal design meets powerful control. FingAI fits perfectly into my workflow.",
    image: AVATAR.testiNine,
  },
];



export interface FAQ  {
   question: string,
   answer: string
}
export const faq: FAQ[] = 
[
  {
    question: "What is FingUI?",
    answer: "FingUI is an AI-powered UI builder that helps you design beautiful, responsive components without writing complex code. Simply describe what you need — and FingUI generates it instantly."
  },
  {
    question: "Do I need design skills to use FingUI?",
    answer: "Nope! FingUI is built for everyone — from beginners to pro developers. You just explain your idea, and FingUI turns it into clean, production-ready UI."
  },
  {
    question: "Does FingUI support light and dark themes?",
    answer: "Yes! FingUI comes with automatic theme toggling. You can seamlessly switch between elegant light mode and sleek dark mode for your components."
  },
  {
    question: "Is FingUI responsive?",
    answer: "Absolutely. Every component generated with FingUI is fully responsive and adapts perfectly to mobile, tablet, and desktop screens."
  },
  {
    question: "Can I customize the components FingUI generates?",
    answer: "Of course! FingUI gives you ready-made components, but you can easily tweak styles, layouts, and animations to match your brand."
  },
]

