
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ui/theme-provider"
import LenisProvider from "@/hooks/LenisProvider";
import { RootProvider } from 'fumadocs-ui/provider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FingUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProvider>
      <LenisProvider>
          
         <ThemeProvider
        attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange
        >
          <Toaster/>
        {/*   <Navbar/> */}
        
           {children}
        
        </ThemeProvider>
      </LenisProvider>
       </RootProvider>
      </body>
    </html>
  );
}
